### ISSUE TITLE
Binaries for arm missing

### ISSUE THREAD

**Issue by pavelschon** [restic/rest-server#114]
I'm trying to use rest-server on arm device, however, binaries of release v0.9.8 are missing at https://github.com/restic/rest-server/releases

Since I don't want to deploy complete toolchain to build from source, I have to stick with v0.9.7.

**Comment by rawtaz** [comment]
Thanks, and sorry about the missing release binaries. The 0.9.8 "release" was just a tag for various reasons.

There will soon[tm] be a new release, and it will include binaries as usual. Until then I'm afraid you'll have to wait.

Let's keep this issue open for the sole purpose of getting you a notice when the new release is out (by closing this issue at that time instead of now).

**Comment by MichaelEischer** [comment]
rest-server 0.10.0 has been released just a few hours ago: https://github.com/restic/rest-server/releases/tag/v0.10.0
