### ISSUE TITLE
README.md is confusing about data location

### ISSUE THREAD

**Issue by telenieko** [restic/rest-server#128]
Hi,

README says:
> By default the server persists backup data in `/tmp/restic`. To start the server with a custom persistence directory and with authentication disabled

But, at least on docker, the default location is `/data`. This is not mentioned on that sentence neither on the section above about Docker.

Maybe it could be clarified.

thanks,
marc

**Comment by rawtaz** [comment]
Thanks for pointing this out. We should improve the README.md such that it's more elaborate on how and where data is stored when running the Docker container.

**Comment by Enrico204** [comment]
The correct path for Docker has been added in the README. There is something else to fix? :-)

**Comment by MichaelEischer** [comment]
The remark on the path for docker seems to have been there since 2017. Maybe it's just hidden too well?

**Comment by rawtaz** [comment]
I noticed that there are two Docker headings - one at the top which is a bit larger than the second one a bit further down. I think these should be consolidated.

I'd suggest moving the things under the first Docker heading to under the second Docker heading, and promoting that second Docker heading to the same size as the first Docker heading (one size bigger, that is).

The rationale is that while a lot of folks use Docker to run rest-server, from a README point of view it makes more sense to layout the text based on the software being the first citizen, rather than Docker. Hence, Docker should come after the more general build and usage information.

I agree that `/data` text is a bit hidden, but it will probably be more obvious when there's just one proper heading and corresponding info for Docker in the README.

**Comment by telenieko** [comment]
> The remark on the path for docker seems to have been there since 2017. Maybe it's just hidden too well?

Yup. I was just reviewing the issue and it took me a while to realise there a two docker sections in the README as noted by @rawtaz 

I just created a PR (#156 ) that merges both sections and puts some emphasis on the "contrary to the defaults" behaviour of the image.
