### ISSUE TITLE
Fork and Die

### ISSUE THREAD

**Issue by AndreaGreco** [restic/rest-server#25]
Hi, there way to let this daemon fork and die.
I see you use systemd, that make it for you.

Use case:
Some NAS not use systemd, then fork and die is required for correct working.
It could it be implemented as command line parameter.
I found [a go lib](https://github.com/takama/daemon) that allow without big effort Fork and Die.

**Comment by fd0** [comment]
You can easily use the standard shell function to background a process with `&` like this:
```
rest-server --path /srv/foo &
```

I don't see a need to add this to the rest server: It will be code that we need to maintain and it makes the program more complex. The new way to start servers is to have the init system (be it systemd, daemontools or something else) handle the forking.

I'm in favor of closing this issue, what do you think @zcalusic?

**Comment by AndreaGreco** [comment]
Bad idea, run server with root permission.

**Comment by fd0** [comment]
So, then setuid() to the correct user before, e.g.:
```
su - nobody -c "rest-server --path /srv/foo" &
```

**Comment by zcalusic** [comment]
Yeah, I agree with @fd0. The ecosystem is going the way of foreground applications only. And it is easy to background/daemonize if/when needed, even if you're not using systemd.

@AndreaGreco, may I suggest using http://www.libslack.org/daemon/ instead of reimplementing its feature set in rest-server? Which would be more code than what we have right now. You should have more than enough features in that useful app to do whatever you want, it is very configurable.

**Comment by pkpowell** [comment]
I put this in `/etc/init/rest-server.conf`on my synology nas (it seems there's no `systemd` on my DS216).
````
start on startup

stop on runlevel [06]

exec /usr/local/bin/rest-server --path /restic/repo/path
````
It'll start on boot, and you can start/stop it with `start rest-server`, `stop rest-server`
