### ISSUE TITLE
Mode in which authenticated users can only access their own directory

### ISSUE THREAD

**Issue by Mebus** [restic/rest-server#37]
Hallo,

rest-server should have a mode in which each individual user can only access it's private directory. For instance "userA" should only be able to access the subdirectory "userA".

Mebus

**Comment by wojas** [comment]
I was planning to implement something like this: I was considering adding a second level to the repos, where you would have /:user/:repo, so that a user can have more than one repo.

Your proposal would be even simpler to implement and could be extended to multiple repos later anyway. I will implement this.

**Comment by wojas** [comment]
Never mind, just noticed the PR 👍

**Comment by Mebus** [comment]
Great! I already created a pull request for this:

https://github.com/restic/rest-server/pull/38

;-)

I am relatively new to go, but this seems to work. Maybe there is a more elegant way to do this...

Mebus

**Comment by Mebus** [comment]
@wojas Can you make a version that uses handlers.AuthHandler and is more elegant?

Mebus

**Comment by zcalusic** [comment]
Closed via #38
