### ISSUE TITLE
rest-server with non-local (Google Cloud, B2, S3..) backend

### ISSUE THREAD

**Issue by padelt** [restic/rest-server#39]
Just starting with `restic` (which actually seems to be "too good to be true"! :-) so maybe I missed a feature. Otherwise: Feature request!?

Having been to all kinds of bad situations, I consider the threat model in https://github.com/restic/restic/issues/784 very real:
"Servers-to-be-backuped" (STBB) are taken over by an adversary trying to delete backups for extortion purposes.
I'd extend it to "admin fat fingers" (accidentally deleting backups from the STBB). So I like the idea of `--append-only` with a dedicated `rest-server` (RS) that doesn't share admin credentials with STBBs.

I would like to let RS store its data on the cloud backends (remote storage) as implemented by `restic`'s client itself: Google Cloud Storage, Backbaze B2, AWS S3, SFTP... (personally interested in GCS and B2)
Why?
- I don't have an RS with adequate storage. 
- I don't want to maintain libraries and credentials for remote storage on all STBB.
- I would like to switch remote storage without reconfiguring a dozen STBBs but only one RS. 

Is this possible with `rest-server`?

Philipp

**Comment by zcalusic** [comment]
Hello @padelt and thanks for the comment.

I'm afraid all Rest Server does is write to locally mounted storage and that's all it's going to do.

From what I understand, you'd like to use it like a proxy to another HTTP based service, but that would mean that all restic libraries needed to access such service would need to be ported over, and that would really be a lot of work. Not to mention maintenance later...

If `--append-only` is what you're after, I guess such flag would need to be supported  by restic client itself, I don't know if that's possible, @fd0 might clarify on this one.

Having said that, if you'd really like to have one central, trusted Rest Server proxy to other services, there might be a "cheat" which could allow you that. If you can mount some of the above mentioned cloud services on your trusted server say via FUSE (lots of implementations out there), then Rest Server can use it just like it was a locally attached disk. Actually, that is what I use currently, Rest Server is a known (SSL & password protected) HTTP endpoint for multiple clients, but it then writes to a distributed filesystem which is mounted locally.

**Comment by padelt** [comment]
Hi @zcalusic , thanks for replying!

> use it like a proxy to another [...] service

Exactly.

> libraries needed to access such service would need to be ported over [to rest-server], and that would really be a lot of work

I agree, it would greatly extend the scope of rest-server.

> would need to be supported by restic client

That wouldn't help as I have to assume that the machine running restic client is compromides.

Mounting via FUSE is something I thought about, too. It would solve a lot of problems in an elegant way. I worry about reliability of that setup though. Long time ago (~years), there was a major catch with all I tried.
What distributed FS backend do you use? If that is reliable for you, I'd really want to try it (again)!

**Comment by zcalusic** [comment]
I use [MooseFS](https://github.com/moosefs/moosefs), it's also FUSE based. Rest Server also has nginx proxy in front of it, which provides SSL, access control, logging... I decided to use only basic Rest Server functionality (REST API), and not export it directly to the public Internet. Mostly because nginx is battle proven in such setups, and it was already there providing such services to other apps.

Both nginx & Rest Server are running as containers on multiple hosts (in Docker swarm), so I even have redundancy, in case some of the hosts is down, or something... and MooseFS provides data redundancy, replicates to multiple hosts.

Yes, all that has been working for months now, completely stable and having no performance impact at all. Several months ago I was doing backup to locally mounted MooseFS, the speed now is the same as I was getting then, even if I now have several more hops to get to the storage eventually.

I suppose the weakest link, if you attempt something like this, is the quality of FUSE implementation you pick.

**Comment by padelt** [comment]
Thanks for the info!
I'd trust MooseFS (or any distributed FS over low-latency, high-reliability links) a lot more than FUSE over the Internet to a cloud provider.
Not sure if I'll try it. If I do, I'll report it here. Until then, this issue might better be closed.

Thinking about it, `rest-server` might actually be a function or command of the `restic`-client (so both `rest-server` and the client work from the same binary). That may allow a feature as I imagined in the future - the libraries would be there and there would "just" be another code path (`rest-server`) using them.

Again, thanks for your help!

**Comment by wojas** [comment]
I do feel it would be nice to have this in rest-server. The main reason I use rest-server is the protection that `--append-only` offers. For my purposes local storage is sufficient, but I can see how it would be useful to support the other backends.

I checked the Restic [Backend interface](https://github.com/restic/restic/blob/master/internal/restic/backend.go) and from a first glance it might be possible to reuse existing Restic backends for storage.

Unfortunately, they are currently hidden as internals, so using them would require moving rest-server inside restic, change restic to allow external access to that part, or maybe vendor/copy those parts. I have also not checked if the backends call much of other restic infrastructure and it they would be safe to use for multiple repos that are being accessed simultaneously.

**Comment by anarcat** [comment]
it seems to me this would mix duties too much. Sure, the rest server supports append-only, but it's not the only goal... it's also designed for better performance and, well, having a HTTP endpoint. The latter is already provided by those cloud providers. It seems to me users would be better served by supporting asymetric, append-only backups natively in Restic (https://github.com/restic/restic/issues/187) rather than complicating the code of this (so far) simpler program.

**Comment by mholt** [comment]
I'm also interested in this (and have commented in the linked restic issue too, because I am not yet sure where it will fall out at).

I'm less interested in `--append-only` as I am in hiding backend storage credentials from backup sources. I'd like to "proxy" those requests through a trusted server, and if that means pluggable backends that implement the handlers in this server, I'd be willing to contribute code to make it happen. (Why are restic's backends internal?) If we are able to reuse those here, that could probably simplify some things a great deal. I don't know about performance implications of doing it this way, maybe there's a better way; I just want to proxy the requests through a trusted server where I set my storage credentials.

**Comment by tarelda** [comment]
Has this idea gained any traction since the original issue creation? 
IMHO, treating REST server as secure proxy to storage backends seems like a best idea complying to my sense of security. Thus I wish it was implemented that way, but not sure if developers are interested and I just have to wait for release or look for another solution.

**Comment by anarcat** [comment]
On 2018-03-06 04:05:29, tarelda wrote:
> Has this idea gained any traction since the original issue creation? 
> IMHO, treating REST server as secure proxy to storage backends seems like a best idea complying to my sense of security. Thus I wish it was implemented that way, but not sure if developers are interested and I just have to wait for release or look for another solution. 

I believe that the rclone backend will provide a REST endpoint that
would fulfill this requirement, in #1561. It wouldn't directly implement
it in rest-server, but would provide equivalent functionality.

**Comment by mholt** [comment]
@padelt @tarelda  I think this is done now: https://github.com/ncw/rclone/issues/2195

Can probably close this issue. :)

**Comment by fd0** [comment]
I think this is superseded by the restic rclone backend. If there's anything missing (and you really need that feature), please add a comment. Thanks!
