### ISSUE TITLE
Make configuration not global

### ISSUE THREAD

**Issue by mholt** [restic/rest-server#66]
I'm using this as a library and would like to start REST servers for different data directories. Currently, [the Config is global](https://github.com/restic/rest-server/blob/7dd5483ea3fa6611a5239fe6638f25751d6b5100/mux.go#L16) and cannot be customized per-mux.

I will submit a PR for this. Do you have any design suggestions for making this change?

**Comment by rawtaz** [comment]
I was thinking about this today as well.

I think to keep it simple you just need to be able to supply multiple `--path` arguments, one per path you want to have repositories in, each having its own `.htaccess` file. The server could simply look for the user in the first path/mux, and if it's not found there look in the next one you specified, etc.

One can start with the requirement that usernames must be unique over all paths (otherwise the first one will be used). So e.g. if user `foo` exists in both of two paths, when `/foo` is used as the path in the URL, the first path's user is used, and the data is stored there.

I don't think the other arguments need to be per-path, let's keep it simple.

**Comment by mholt** [comment]
Specifically, I want a `NewMux()` to be associated with its own `Config` -- it has nothing to do with `Config.Path` in particular, and my use case definitely doesn't have anything to do with `.htaccess` files.

Maybe something like `restserver.NewMux(restConfig)` where `restConfig := restserver.Config{...}`. But I'm not sure how to attach the mux to the config.

**Comment by mholt** [comment]
I think we're talking about two different things then; I am using rest-server as a library, so there is no user interface in my case. But I can understand the need to bridge the two.

**Comment by rawtaz** [comment]
Got ya. I for some reason presumed that it would be something that should be exposed on the command line as well, but I understand you're just looking at the internals then. I think once those are in place it's a pretty small thing to make it accessible through the CLI as well. So never mind me.
