### ISSUE TITLE
Don't do mkdirAll, if a directory is missing

### ISSUE THREAD

**Issue by TheDreamer** [restic/rest-server#92]
Been trying to figure out why something keeps recreating my restic repo...and blocking the system from mounting my restic repo.

Was adding all kinds of extra tests to ensure that services wait for  the volume to appear, which can take a while (sometimes hours) after bouncing raid box.  Turns out the problem is on the other side of the bounce, where volume has disappeared, but rest-server refuses to accept that, and makes the mountpoint non-empty and blocks it from ever coming back.

The mkdirAll was the fix for issue #40 

WIsh I had snapped out that new NAS back when I thought I could afford one....

**Comment by rawtaz** [comment]
@TheDreamer Can you elaborate on this a bit? What folders are recreated in a way that you don't want?

**Comment by gbolo** [comment]
@rawtaz I belive he is mounting an external volume (such as NFS) for the `data` directory of restic-rest-server. Seems like when the volume disappears (perhaps due to network or storage maintance), the rest-server does not like that and pollutes the now empty mount point with new folders. This seems to prevent his server from mounting the volume again when it comes back online. This is how I interpret it anyways. @TheDreamer is that correct?

**Comment by rawtaz** [comment]
Closing this, not because it wasn't a valid concern, but because we don't generally hear about this being a problem. I think the folder creation is there for a valid reason, and it is fair of rest-server to expect the path where it's asked to store repositories to be ready for use. Feel free to add more comments though. If this is a problem for many users we can always revisit it.
